
env_id: "Intersection-Lag-v0"
seed: 42
num_envs: 4
num_steps: 128
epochs: 50  # Reduced for quick test
update_epochs: 5
minibatch_size: 128
lr: 0.0003
gamma: 0.99
gae_lambda: 0.95
clip_ratio: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
save_gif_freq: 25
checkpoint: false

# Lagrangian
lambda_init: 0.0
lambda_lr: 0.001
cost_limit: 5.0

# Environment
target_pos: [1.5, 0.0]
max_accel: 3.2
dt: 0.1
robot_radius: 0.3328
v_limit: 1.5

# Reward weights
w_progress: 17.11
w_overspeed: 72.7
w_comfort: 0.697
w_time_penalty: 0.1
reward_success: 50.0
reward_collision: -100.0

# Cost weights  
cost_scale_mu: 463.2
cost_crash: 100.0
